require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeaponsController do

  # This should return the minimal set of attributes required to create a valid
  # Weapon. As you add validations to Weapon, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all weapons as @weapons" do
      weapon = Weapon.create! valid_attributes
      get :index
      assigns(:weapons).should eq([weapon])
    end
  end

  describe "GET show" do
    it "assigns the requested weapon as @weapon" do
      weapon = Weapon.create! valid_attributes
      get :show, :id => weapon.id
      assigns(:weapon).should eq(weapon)
    end
  end

  describe "GET new" do
    it "assigns a new weapon as @weapon" do
      get :new
      assigns(:weapon).should be_a_new(Weapon)
    end
  end

  describe "GET edit" do
    it "assigns the requested weapon as @weapon" do
      weapon = Weapon.create! valid_attributes
      get :edit, :id => weapon.id
      assigns(:weapon).should eq(weapon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Weapon" do
        expect {
          post :create, :weapon => valid_attributes
        }.to change(Weapon, :count).by(1)
      end

      it "assigns a newly created weapon as @weapon" do
        post :create, :weapon => valid_attributes
        assigns(:weapon).should be_a(Weapon)
        assigns(:weapon).should be_persisted
      end

      it "redirects to the created weapon" do
        post :create, :weapon => valid_attributes
        response.should redirect_to(Weapon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weapon as @weapon" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weapon.any_instance.stub(:save).and_return(false)
        post :create, :weapon => {}
        assigns(:weapon).should be_a_new(Weapon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weapon.any_instance.stub(:save).and_return(false)
        post :create, :weapon => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weapon" do
        weapon = Weapon.create! valid_attributes
        # Assuming there are no other weapons in the database, this
        # specifies that the Weapon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Weapon.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => weapon.id, :weapon => {'these' => 'params'}
      end

      it "assigns the requested weapon as @weapon" do
        weapon = Weapon.create! valid_attributes
        put :update, :id => weapon.id, :weapon => valid_attributes
        assigns(:weapon).should eq(weapon)
      end

      it "redirects to the weapon" do
        weapon = Weapon.create! valid_attributes
        put :update, :id => weapon.id, :weapon => valid_attributes
        response.should redirect_to(weapon)
      end
    end

    describe "with invalid params" do
      it "assigns the weapon as @weapon" do
        weapon = Weapon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weapon.any_instance.stub(:save).and_return(false)
        put :update, :id => weapon.id, :weapon => {}
        assigns(:weapon).should eq(weapon)
      end

      it "re-renders the 'edit' template" do
        weapon = Weapon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weapon.any_instance.stub(:save).and_return(false)
        put :update, :id => weapon.id, :weapon => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weapon" do
      weapon = Weapon.create! valid_attributes
      expect {
        delete :destroy, :id => weapon.id
      }.to change(Weapon, :count).by(-1)
    end

    it "redirects to the weapons list" do
      weapon = Weapon.create! valid_attributes
      delete :destroy, :id => weapon.id
      response.should redirect_to(weapons_url)
    end
  end

end
